<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="AddEvent.aspx.cs" Inherits="AddEvent" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
    <table style="width: 100%">
        <tr>
            <td style="width: 5%">&nbsp;</td>
            <td style="width: 90%">&nbsp;</td>
            <td style="width: 5%">&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>

                <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" DataKeyNames="user_id,event_id" DataSourceID="Eventer" Width="796px">
                    <Columns>
                        <asp:BoundField DataField="event_name" HeaderText="Event Name" SortExpression="event_name" />
                        <asp:BoundField DataField="type" HeaderText="Type" SortExpression="type" />
                        <asp:BoundField DataField="number_of_guests" HeaderText="Number Of Guests" SortExpression="number_of_guests" />
                        <asp:BoundField DataField="date" HeaderText="Date" SortExpression="date" />
                        <asp:BoundField DataField="location" HeaderText="Location" SortExpression="location" />
                    </Columns>
                </asp:GridView>


                <asp:SqlDataSource ID="Eventer" runat="server" ConnectionString="<%$ ConnectionStrings:EventerConnectionString %>" SelectCommand="SELECT * FROM [Event]"></asp:SqlDataSource>


            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <asp:Button ID="Choose_Event_CMD" runat="server" Text="Choose Event" />
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </table>


    <div id="doc" class="yui-t1">
      <div id="hd">
        <div id="header"><h1><a href="http://www.free-css.com/free-css-layouts.php">Free CSS Layouts</a></h1></div>
      </div>
      <div id="bd">
        <div id="yui-main">
          <div class="yui-b">
            <div class="content">Content Here</div>
          </div>
        </div>
        <div class="yui-b">
          <div id="secondary">Secondary Column</div>
        </div>
      </div>
      <div id="ft">
        <div id="footer">Footer</div>
      </div>
    </div>

</asp:Content>

